name: Generate design tokens

on:
  repository_dispatch:
    types: update-tokens

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Busca os commits do repo

      - name: Create input JSON # Criar o arquivo input.json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.filename }} # Obtendo o nome do arquivo
          json: ${{ github.event.client_payload.tokens }} # Obtendo os dados JSON do payload para o arquivo
          dir: 'input' # Jogando o arquivo para a pasta

      - name: Install Node.js # Instalação do NODE
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci # Praticamente um "npm i" para rodando dentro de ambiente ci/cd

      - name: Build
        run: npm run build

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'style: Update design tokens'
          title: ${{ github.event.client_payload.commitMessage || 'Update design tokens' }} # Settando o title da PR com o campo "commitMessage" ou com o texto padrão
          body: 'Design tokens have been updated via Figma and need to be reviewed.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
